Algoritmo "Soma"
// Algoritimo utilizado para realizar soma
Var
// Seção de Declarações das variáveis 
primeironumero, segundonumero, soma: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite um número: ")
leia (primeironumero)
escreva ("Digite outro número: ")
leia (segundonumero)

soma <- primeironumero+ segundonumero

limpatela

escreva ("Soma = ", soma)
Fimalgoritmo