Algoritmo "laço de repetição, contador par de 100 a 200"
// Professor   : Carlos Anderson
// Descrição   : Algoritmo para contar de 100 até 200 mostrando apenas os números pares
// Autor(a)    : Artur Ribeiro Cana Brasil
// Data atual  : 18/04/2023
Var
// Seção de Declarações das variáveis 
i :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 100 ate 200 passo 2 faca
escreval (i)
fimpara
Fimalgoritmo