Algoritmo "Tabuada de multiplicação usando laço de repetição"
// Professor   : Carlos Anderson
// Descrição   : Aqui é gerado a tabuada de multiplicação
// Autor(a)    : Artur Ribeiro Cana Brasil
// Data atual  : 12/04/2023
Var
   // Variáveis utilizadas
   i, j, calculo :inteiro

Inicio
   // realização de comandos
   j <-5
   para i de 1 ate 10 faca
      calculo <- i*j
      escreval (j, " X", i, " =", calculo)
   fimpara
Fimalgoritmo